In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data - Sheet2.csv")

In [3]:
df.head(5)

Feature-1   Feature-2  Class Label
0   60.989534  506.082788            0
1    4.552524   78.479751            0
2  130.764991  245.881327            0
3  232.025160  745.337567            0
4   39.645334  667.743960            0

In [4]:
X = df.drop(["Class Label"],axis = 1)
y = df["Class Label"]

In [5]:
X,y
#1998 rows


(       Feature-1   Feature-2
 0      60.989534  506.082788
 1       4.552524   78.479751
 2     130.764991  245.881327
 3     232.025160  745.337567
 4      39.645334  667.743960
 ...          ...         ...
 1993    1.229802  263.751488
 1994   63.012099  247.358797
 1995   77.959464  143.492312
 1996   23.826663  357.297253
 1997   46.397667   34.017045
 
 [1998 rows x 2 columns],
 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 1993    1
 1994    1
 1995    1
 1996    1
 1997    1
 Name: Class Label, Length: 1998, dtype: int64)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test1,y_train,y_test1 = train_test_split(X,y,test_size = 0.3,random_state = 42)
X_validation,X_test,y_validation,y_test = train_test_split(X_test1,y_test1,test_size = 0.33,random_state = 42)

In [8]:
X_test.shape

(198, 2)

In [9]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()

GNB.fit(X_train, y_train)

# Output Prediction
predicted = GNB.predict(X_test)


In [10]:
print(f"Actual_value:{y_test}")
print(f"Predicted_value:{predicted}")

Actual_value:1284    1
1759    1
613     0
1198    1
1464    1
       ..
1125    1
1280    1
218     0
909     0
480     0
Name: Class Label, Length: 198, dtype: int64
Predicted_value:[1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1
 0 1 0 1 0 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 0
 1 0 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0
 0 0 0 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 1 0
 0 1 0 1 0 0 1 1 1 1 0 0 1]


In [11]:
from sklearn.metrics import accuracy_score,f1_score

accuracy = accuracy_score(predicted, y_test)
f1 = f1_score(predicted, y_test, average="weighted")

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")

Accuracy: 0.8939393939393939
F1 Score: 0.8944517640169813


In [12]:
# For both the categories compute: (i) Mean (ii) Covariance
# Matrix.
# df[(df["Feature-1"]) & (df["Class Label"]==0)] This wont work because 1st feature is non boolean type rather float
df1 = df[(~df["Feature-1"].isnull()) & (df["Class Label"] == 0)]
df1.mean()

Feature-1      150.179968
Feature-2      502.764772
Class Label      0.000000
dtype: float64

In [13]:
df2 = df[(~df["Feature-1"].isnull()) & (df["Class Label"] == 1)]
df2.mean()

Feature-1       45.173738
Feature-2      200.346970
Class Label      1.000000
dtype: float64

In [14]:
df3 = df[(~df["Feature-2"].isnull()) & (df["Class Label"] == 0)]
df3.mean()

Feature-1      150.179968
Feature-2      502.764772
Class Label      0.000000
dtype: float64

In [15]:
df4 = df[(~df["Feature-2"].isnull()) & (df["Class Label"] == 1)]
df4.mean()

Feature-1       45.173738
Feature-2      200.346970
Class Label      1.000000
dtype: float64

In [16]:
np.cov(df1["Feature-1"],df1["Class Label"])


array([[7274.99116657,    0.        ],
       [   0.        ,    0.        ]])

In [17]:
np.cov(df2["Feature-1"],df2["Class Label"])

array([[675.40971162,   0.        ],
       [  0.        ,   0.        ]])

In [18]:
np.cov(df3["Feature-2"],df3["Class Label"])

array([[82422.61505572,     0.        ],
       [    0.        ,     0.        ]])

In [19]:
np.cov(df4["Feature-2"],df4["Class Label"])

array([[13504.08218254,     0.        ],
       [    0.        ,     0.        ]])